// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

type Link struct {
	ID         int64  `json:"id"`
	Url        string `json:"url"`
	Commentary string `json:"commentary"`
}
